import os

PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
DATASETS_DIR = 'datasets'
DATASETS_PATH = os.path.join(PROJECT_ROOT, DATASETS_DIR)
BOOKINGS_FILE = f'{DATASETS_DIR}/bookings.csv'
EVENTS_FILE = f'{DATASETS_DIR}/events.csv'
WEATHER_FILE = f'{DATASETS_DIR}/weather.csv'

API_PORT = 8000
DASHBOARD_PORT = 8501

DEFAULT_FORECAST_PERIODS = 30
DEFAULT_RECOMMENDATIONS = 5
DEFAULT_ITINERARY_DAYS = 3
DEFAULT_EVENTS_PER_DAY = 3
DEFAULT_RECOMMENDATION_DAYS = 10

PERSONAS_CLUSTERS = 3
RANDOM_STATE = 42
SIMILAR_USERS_COUNT = 10

DATASET_START_DATE = '2023-12-01'
DATASET_END_DATE = '2026-02-28'

DATASET_N_ACCOMMODATIONS = 50
DATASET_BASE_BOOKINGS_PER_DAY = 100
DATASET_MIN_BOOKINGS_PER_DAY = 50
DATASET_MAX_BOOKINGS_PER_DAY = 200

